name: task_master
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1 # substitua pela versão mais recente
  google_sign_in: ^6.2.1 # para autenticação com Google
  firebase_core: ^3.6.0 
  passwordfield: ^0.2.0
  intl: ^0.19.0
  provider: ^6.1.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/Icon.jpeg
