// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOgLBS-plgodf67TlmGl87cf9perX_syg',
    appId: '1:646686539960:web:6ec7f6272006396e4ff44d',
    messagingSenderId: '646686539960',
    projectId: 'taskmaster-9855f',
    authDomain: 'taskmaster-9855f.firebaseapp.com',
    storageBucket: 'taskmaster-9855f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc1PK9_byWqU0-hO8VYaobPaxL1Kh9GLg',
    appId: '1:646686539960:android:3bfd8bd525849d9f4ff44d',
    messagingSenderId: '646686539960',
    projectId: 'taskmaster-9855f',
    storageBucket: 'taskmaster-9855f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfDvts6HffZNCjqBlam4kZ-UNB9K3xWBE',
    appId: '1:646686539960:ios:4750ce7c5f4eaa994ff44d',
    messagingSenderId: '646686539960',
    projectId: 'taskmaster-9855f',
    storageBucket: 'taskmaster-9855f.appspot.com',
    iosBundleId: 'com.example.taskMaster',
  );
}
